### ISSUE TITLE
Image replacements

### ISSUE THREAD

**Issue by ukshat** [ukshat/AlienAnnexation#8]
Replace each image with a new one so that none of JrJava's images are being used.
Image list
- [x] ship
- [x] missile
- [x] torpedo
- [x] alien(s)
- [x] background
- [x] "game iver"

**Comment by ukshat** [comment]
![ship.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bbd7c63e4522a00110a6cf8/125516c66e82c728ace21e0d46fb9c9333c0cfeb9ffbb049a15ee4d6730472712b00f4282683b37cbc147d035f5f49a4450b5b41aeff9b37b4f46d2ede0356b49b381d66cc2f10aab2831abc08bf278d4e86b7b98b4ad2a5.png)

**Comment by FartHeadedLegend** [comment]
![unnamed.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc286935c46100012bca922/125516c66e82c728ace21e0d46fd9a94228f86adcda5fd53b652fa912a5265296b51a12974d2e07eb9122f0259091cac415f5740affd8c79a0a42062c80d55b98e30063e937f03a6aa8316b500bf23824a82b0be8a45c3e83c37aa.png)

**Comment by FartHeadedLegend** [comment]
![unnamed.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc286935c46100012bca922/125516c66e82c728ace21e0d46fd9a94228f86adcda5fd53b652fa912a5265296b51a12974d2e07eb9122f0259091cac415f5740affd8c79a0a42062c80d55b98e30063e937f03a6aa8318b500bf23824a8db5bd8b44c9ea3837aa.png)

**Comment by FartHeadedLegend** [comment]
![2018-10-14.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc286935c46100012bca922/125516c66e82c728ace21e0d46bac4cb7bcfd2f9c2b8eb01e81fe086264c22703d46f9692587e12ce8412d075f5b1daa170a5f44fbf18d78a2b36e76984019af80330b2b9b645bf9fa9015ad00bd2a8a4a86bfb9824fc1eb3d22e28d9d02.png)

**Comment by FartHeadedLegend** [comment]
![unnamed.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc286935c46100012bca922/125516c66e82c728ace21e0d46fd9a94228f86adcda5fd53b652fa912a5265296b51a12974d2e07eb9122f0259091cac415f5740affd8c79a0a42062c80d55b98e30063e937f03a6aa8318b500bf23824a8db5bd8f4bc3e83b37aa.png)

**Comment by FartHeadedLegend** [comment]
![2018-10-14.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc286935c46100012bca922/125516c66e82c728ace21e0d46bac4cb7bcfd2f9c2b8eb01e81fe086264c22703d46f9692587e12ce8412d075f5b1daa170a5f44fbf18d78a2b36e76984019af80330b2b9b645bf9fa9015ad00b32a8a4a86bfb9824fc2ea3c2de68c9d02.png)

**Comment by FartHeadedLegend** [comment]
[Uploading unnamed.png...]

**Comment by FartHeadedLegend** [comment]
![unnamed.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc286935c46100012bca922/125516c66e82c728ace21e0d46fd9a94228f86adcda5fd53b652fa912a5265296b51a12974d2e07eb9122f0259091cac415f5740affd8c79a0a42062c80d55b98e30063e937f03a6aa8316b500bf23824987b4bb834ec0e83d37aa.png)

**Comment by FartHeadedLegend** [comment]
![unnamed.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc286935c46100012bca922/125516c66e82c728ace21e0d46fd9a94228f86adcda5fd53b652fa912a5265296b51a12974d2e07eb9122f0259091cac415f5740affd8c79a0a42062c80d55b98e30063e937f03a6aa8317b500bf23824987b4b48849c9ed3f37aa.png)

**Comment by FartHeadedLegend** [comment]
![unnamed.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc286935c46100012bca922/125516c66e82c728ace21e0d46fd9a94228f86adcda5fd53b652fa912a5265296b51a12974d2e07eb9122f0259091cac415f5740affd8c79a0a42062c80d55b98e30063e937f03a6aa8316b500bf23824987b4b58a4cc7ef3537aa.png)

**Comment by FartHeadedLegend** [comment]
![hireslargecomposite.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc286935c46100012bca922/125516c66e82c728ace21e0d46e09d8826918fa89deeba40ab50e09b3a4f33766b48e13b628ae92dbc56395b4d5a1cfe155f0c42aaf98d78a0e06e708a5b03e982695a26c02f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e482894d3d1a071089fa5927ed.png)

**Comment by FartHeadedLegend** [comment]
![hireslargecomposite.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc286935c46100012bca922/125516c66e82c728ace21e0d46e09d8826918fa89deeba40ab50e09b3a4f33766b48e13b628ae92dbc56395b4d5a1cfe155f0c42aaf98d78a0e06e708a5b03e982695a26c02f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e482894d3d16061b8af95c27ed.png)

**Comment by FartHeadedLegend** [comment]
![hireslargecomposite.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc286935c46100012bca922/125516c66e82c728ace21e0d46e09d8826918fa89deeba40ab50e09b3a4f33766b48e13b628ae92dbc56395b4d5a1cfe155f0c42aaf98d78a0e06e708a5b03e982695a26c02f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e482894d3a1e051d8bf65b27ed.png)

**Comment by FartHeadedLegend** [comment]
![hireslargecomposite.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc286935c46100012bca922/125516c66e82c728ace21e0d46e09d8826918fa89deeba40ab50e09b3a4f33766b48e13b628ae92dbc56395b4d5a1cfe155f0c42aaf98d78a0e06e708a5b03e982695a26c02f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e482894d3a1e071e8df75827ed.png)

**Comment by FartHeadedLegend** [comment]
![hireslargecomposite.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc286935c46100012bca922/125516c66e82c728ace21e0d46e09d8826918fa89deeba40ab50e09b3a4f33766b48e13b628ae92dbc56395b4d5a1cfe155f0c42aaf98d78a0e06e708a5b03e982695a26c02f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e482894d3a1f051b81ff5527ed.png)

**Comment by FartHeadedLegend** [comment]
![hireslargecomposite.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc286935c46100012bca922/125516c66e82c728ace21e0d46e09d8826918fa89deeba40ab50e09b3a4f33766b48e13b628ae92dbc56395b4d5a1cfe155f0c42aaf98d78a0e06e708a5b03e982695a26c02f0dbefad341eb5ee779c11ac7a4b6984dc6e23c20e482894d3a1f001a80f65f27ed.png)
